site_name: CodeIgniter Minifier
site_description: Documentation for asset minification and versioning library for CodeIgniter 4

theme:
  name: material
  logo: assets/flame.svg
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant

extra:
  homepage: https://michalsn.github.io/minifier

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/michalsn/minifier
      name: GitHub

site_url: https://michalsn.github.io/minifier/
repo_url: https://github.com/michalsn/minifier
edit_uri: edit/develop/docs/

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false

extra_css:
  - assets/github-dark-dimmed.css

extra_javascript:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.6.0/build/highlight.min.js
  - assets/hljs.js

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Basic Usage: basic-usage.md
